### ISSUE TITLE
Update eslint

### ISSUE THREAD

**Issue by hugovk** [nordsoftware/react-boilerplate#3]
https://github.com/nordsoftware/react-boilerplate/blob/master/package.json#L45

The current version is causing an error on Code Climate:
```
/usr/src/app/node_modules/eslint/lib/config/config-validator.js:102
        throw new Error(message.join(""));
        ^

Error: /code/.eslintrc:
	Configuration for rule "eol-last" is invalid:
	Value "always" must be an enum value.

    at validateRuleOptions (/usr/src/app/node_modules/eslint/lib/config/config-validator.js:102:15)
    at /usr/src/app/node_modules/eslint/lib/config/config-validator.js:148:13
    at Array.forEach (native)
    at Object.validate (/usr/src/app/node_modules/eslint/lib/config/config-validator.js:147:35)
    at Object.load (/usr/src/app/node_modules/eslint/lib/config/config-file.js:394:19)
    at loadConfig (/usr/src/app/node_modules/eslint/lib/config.js:74:33)
    at getLocalConfig (/usr/src/app/node_modules/eslint/lib/config.js:177:23)
    at Config.getConfig (/usr/src/app/node_modules/eslint/lib/config.js:272:22)
    at CLIEngine.getConfigForFile (/usr/src/app/node_modules/eslint/lib/cli-engine.js:715:29)
    at module.exports (/usr/src/app/lib/validate_config.js:9:22)
```
https://codeclimate.com/github/nordsoftware/react-boilerplate/builds/1

Updating eslint should help:
https://github.com/airbnb/javascript/issues/1088#issuecomment-249372844

**Comment by cniska** [comment]
@hugovk I'm pretty sure that the **eslint** version used in `package.json` is the issue, because we are using the latest version (**3.12.2**). Maybe we should escalate this issue to Code Climate?

**Comment by hugovk** [comment]
@crisu83 Support request sent to Code Climate.

**Comment by hugovk** [comment]
Fixed by https://github.com/nordsoftware/react-boilerplate/pull/9.
